# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Catenology Framework
description: > # this means to ignore newlines until "baseurl:"
  The frontend toolkit that powers Catenology websites.
baseurl: "" # the subpath of your site, e.g. /blog
url: "catfw.catenology.com" # the base hostname & protocol for your site
# url: "127.0.0.1:4000" # for local testing
# Build settings
markdown: kramdown
